//
//  CharacterDetailsModels.swift
//  RickAndMorty_Test
//
//  Created by Muraviov Kyrylo on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterDetails {
    
  enum GetCharacter {
      
    struct Request {
    }
      
    struct Response {
        var character: CharacterEntity
    }
      
    struct ViewModel {
        
        struct DisplayedCharacter {
            var id: Int64
            var name: String?
            var created: String?
            var gender: String?
            var image: UIImage?
            var species: String?
            var status: String?
        }
        
        var displayedCharacter: DisplayedCharacter
    }
  }
}
