//
//  CharacterDetailsRouter.swift
//  RickAndMorty_Test
//
//  Created by Muraviov Kyrylo on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsRoutingLogic {
}

protocol CharacterDetailsDataPassing {
    var dataStore: CharacterDetailsDataStore? { get }
}

class CharacterDetailsRouter: CharacterDetailsDataPassing {
    
    // MARK: - External vars
    weak var viewController: CharacterDetailsViewController?
    
    // MARK: - Internal vars
    var dataStore: CharacterDetailsDataStore?
}

// MARK: - Routing logic implementation
extension CharacterDetailsRouter: CharacterDetailsRoutingLogic {
}
