//
//  CharacterDetailsInteractor.swift
//  RickAndMorty_Test
//
//  Created by Muraviov Kyrylo on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharacterDetailsBusinessLogic {
    func getCharacter(request: CharacterDetails.GetCharacter.Request)
}

protocol CharacterDetailsDataStore {
    var character: CharacterEntity! { get set }
}

class CharacterDetailsInteractor: CharacterDetailsDataStore {
    
    // MARK: - Internal vars
    var character: CharacterEntity!
    var presenter: CharacterDetailsPresentationLogic?
}

// MARK: - Business logic implementation
extension CharacterDetailsInteractor: CharacterDetailsBusinessLogic {
    func getCharacter(request: CharacterDetails.GetCharacter.Request) {
        let response = CharacterDetails.GetCharacter.Response(character: character)
        presenter?.presentCharacter(response: response)
    }
}
