//
//  CharactersListInteractor.swift
//  RickAndMorty_Test
//
//  Created by Muraviov Kyrylo on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CharactersListBusinessLogic
{
  func doSomething(request: CharactersList.Something.Request)
}

protocol CharactersListDataStore
{
  //var name: String { get set }
}

class CharactersListInteractor: CharactersListBusinessLogic, CharactersListDataStore
{
  var presenter: CharactersListPresentationLogic?
  var worker: CharactersListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CharactersList.Something.Request)
  {
    worker = CharactersListWorker()
    worker?.doSomeWork()
    
    let response = CharactersList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
