//
//  CharacterListModels.swift
//  RickAndMorty
//
//  Created by Muraviov Kyrylo on 30.03.2025.
//  Copyright (c) 2025 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterList {
    
    struct Request {
        let page: Int
    }
    
    struct Response {
        let characters: [CharacterEntity]
    }
    
    struct ViewModel {
        
        struct DisplayCharacter {
            let id: Int64
            let name: String?
            var image: UIImage?
            let status: String?
        }
        
        let characters: [DisplayCharacter]
    }
}
